CC = cc

all:
	$(CC) create.c -o create
	$(CC) delete.c -o delete
	$(CC) remove.c -o remove
	$(CC) view.c -o view
	$(CC) copy_to_disk.c -o copy_to_disk
	$(CC) copy_from_disk.c -o copy_from_disk
	$(CC) list_files.c -o list_files

clean:
	rm create delete remove view virtual_disk copy_from_disk copy_to_disk list_files